// src/locales/es.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " en {seconds}s",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} pts)",
        "scoreEntry": "{rank}. {name} ({score} pts)",
        "roundText": {
            "one": "una ronda",
            "many": "{totalRounds} rondas"
        },
        "roundPrefixParen": "(Ronda {currentRound}/{totalRounds}) "
    },
    "trivia": {
        "start": "🎯 ¡Empezando {roundText} de Trivia! Tema: {topic}. Tienes {questionTimeSeconds} segundos para responder cada pregunta. ¡Escribe tus respuestas en el chat!",
        "roundPrefix": "[Ronda {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} TRIVIA: {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ ¡@{displayName} acertó{timeString}{streakInfo}{pointsInfo}! La respuesta es: {answer}. {explanation}",
        "timeout": "{roundPrefix}⏱️ ¡Se acabó el tiempo! La respuesta es: {answer}. {explanation}",
        "stop": "{roundPrefix}🛑 Partida detenida. La respuesta era: {answer}",
        "nextRound": "🎮 Empezando ronda {roundNumber} de {totalRounds}...",
        "noScores": "No hay puntuaciones registradas.",
        "help": {
            "base": "🎮 Comandos de Trivia: !trivia (inicia una partida de cultura general), !trivia [topic] [rounds] (tema específico), !trivia game [rounds] (según el juego actual del stream), !trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <opciones...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". Los mods pueden usar comandos adicionales."
        },
        "gameStoppedScores": "🏁 Partida detenida. Puntuaciones finales: {list}",
        "finalScores": "🏁 Puntuaciones finales: {list}"
    },
    "riddle": {
        "start": "🤔 ¡Iniciando {roundText} de acertijos! {topicText} Tienes {questionTimeSeconds} segundos para responder. ¡Escribe tus respuestas en el chat!",
        "topicText": "Tema: {topic}",
        "noTopicText": "¡Tengo un acertijo para ti!",
        "roundPrefix": "[Acertijo {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ ACERTIJO: {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ ¡@{displayName} lo resolvió{timeString}{pointsInfo}! La respuesta es: {answer}.{explanationText}",
        "timeout": "{roundPrefix}⏱️ ¡Tiempo agotado! La respuesta era: {answer}.{explanationText}",
        "stop": "{roundPrefix}🛑 Juego de acertijos detenido.{explanationText}",
        "stopExplanation": " La respuesta era: {answer}. {explanation}",
        "stopAnswerOnly": " La respuesta era: {answer}.",
        "noScores": "No se registraron puntuaciones en esta sesión de acertijos.",
        "sessionScores": "🏁 Mejores jugadores de la sesión de acertijos: {list}",
        "noLeaderboard": "¡Aún no hay estadísticas de acertijos para #{channelName}!",
        "leaderboard": "🏆 Maestros de los acertijos en #{channelName}: {list}",
        "leaderboardEntry": "{rank}. {name} ({points} pts, {solved} resueltos)",
        "help": {
            "base": "🤔 Comandos de acertijos: !riddle (general/juego actual), !riddle <tema> [<rondas>], !riddle <rondas>, !riddle game [<rondas>]",
            "common": ", !riddle leaderboard, !riddle report <motivo>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <fácil|normal|difícil> | questiontime <seg> | pointsbase <núm> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <núm> | keywordslimit <núm> | rounddelay <ms>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}El acertijo ha terminado. La respuesta era: {answer}. {explanation}"
    },
    "geo": {
        "startGame": "🎮 ¡Comenzó el Geo-Game!{roundInfo} ¡Adivina la ubicación del juego{gameTitleText}! {durationInfo} ¡Escribe tus respuestas en el chat! Primera pista en breve...",
        "startReal": "🌍 ¡Comenzó el Geo-Game!{regionInfo}{roundInfo} ¡Adivina la ciudad, monumento o lugar del mundo real! {durationInfo} ¡Escribe tus respuestas en el chat! Primera pista en breve...",
        "roundInfo": " ({totalRounds} rondas)",
        "durationInfo": "Tienes ⏱️ {roundDurationMinutes} minutos por ronda.",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (Región: {regionScope})",
        "nextRound": "🏁 ¡Ronda {currentRound}/{totalRounds} en marcha! ¡Buena suerte!",
        "clue": "❓ Pista {clueNumber}: {clueText}",
        "correctGuess": "✅ ¡Felicidades @{displayName}! Adivinaste: {locationName}{timeMsg}{streakInfo}{pointsInfo}!",
        "timeout": "⏱️ ¡Tiempo agotado! La respuesta correcta era: {locationName}",
        "stopWithAnswer": "🛑 Geo-Game detenido. La respuesta era: {locationName}",
        "stop": "🛑 Geo-Game detenido.",
        "reveal": "📢 ¡La respuesta era: {locationName}! {revealText}",
        "noScores": "No hay puntuaciones registradas para esta sesión.",
        "sessionScores": "Mejores jugadores: {list}",
        "gameEndedScores": "🏁 Juego terminado. Puntuaciones finales de la sesión: {list}",
        "finalScores": "🏁 Puntuaciones finales de la sesión: {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} adivinó: {locationName}{timeString}{streakInfo}{pointsInfo}! ",
            "timeout": "{roundPrefix}⏱️ ¡Tiempo agotado! La ubicación era {locationName}. ",
            "stopped": "{roundPrefix}🛑 Juego detenido. La ubicación era {locationName}. ",
            "reveal": "{roundPrefix}📢 ¡La respuesta era: {locationName}! "
        },
        "roundError": "Ocurrió un error al revelar la respuesta de la ronda {currentRound}.",
        "roundEnded": "La ronda ha terminado."
    }
};
