// src/locales/fr.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " en {seconds}s",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} pts)",
        "scoreEntry": "{rank}. {name} ({score} pts)",
        "roundText": {
            "one": "une manche",
            "many": "{totalRounds} manches"
        },
        "roundPrefixParen": "(Manche {currentRound}/{totalRounds}) "
    },
    "trivia": {
        "start": "🎯 Lancement de {roundText} de Trivia ! Thème : {topic}. Vous avez {questionTimeSeconds} secondes pour répondre à chaque question. Tapez vos réponses dans le chat !",
        "roundPrefix": "[Manche {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} TRIVIA : {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} a trouvé{timeString}{streakInfo}{pointsInfo} ! La réponse est : {answer}. {explanation}",
        "timeout": "{roundPrefix}⏱️ Temps écoulé ! La réponse est : {answer}. {explanation}",
        "stop": "{roundPrefix}🛑 Partie arrêtée. La réponse était : {answer}",
        "nextRound": "🎮 Début de la manche {roundNumber} sur {totalRounds}...",
        "noScores": "Aucun score enregistré.",
        "help": {
            "base": "🎮 Commandes Trivia : !trivia (lance une partie de culture générale), !trivia [thème] [manches] (thème précis), !trivia game [manches] (basé sur le jeu du stream), !trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <options...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". Les mods ont accès à des commandes supplémentaires."
        },
        "gameStoppedScores": "🏁 Partie arrêtée. Scores finaux : {list}",
        "finalScores": "🏁 Scores finaux : {list}"
    },
    "riddle": {
        "start": "🤔 C'est parti pour {roundText} d'énigmes ! {topicText} Vous avez {questionTimeSeconds} secondes pour répondre. Écrivez vos réponses dans le chat !",
        "topicText": "Thème : {topic}",
        "noTopicText": "J'ai une énigme pour vous !",
        "roundPrefix": "[Énigme {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ ÉNIGME : {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} a trouvé{timeString}{pointsInfo} ! La réponse est : {answer}.{explanationText}",
        "timeout": "{roundPrefix}⏱️ Temps écoulé ! La réponse était : {answer}.{explanationText}",
        "stop": "{roundPrefix}🛑 Partie d'énigmes arrêtée.{explanationText}",
        "stopExplanation": " La réponse était : {answer}. {explanation}",
        "stopAnswerOnly": " La réponse était : {answer}.",
        "noScores": "Aucun score enregistré pour cette session d'énigmes.",
        "sessionScores": "🏁 Meilleurs joueurs de la session d'énigmes : {list}",
        "noLeaderboard": "Aucune stat d'énigmes trouvée pour #{channelName} pour le moment !",
        "leaderboard": "🏆 Maîtres des énigmes sur #{channelName} : {list}",
        "leaderboardEntry": "{rank}. {name} ({points} pts, {solved} résolues)",
        "help": {
            "base": "🤔 Commandes d'énigmes : !riddle (général/partie en cours), !riddle <sujet> [<manches>], !riddle <manches>, !riddle game [<manches>]",
            "common": ", !riddle leaderboard, !riddle report <raison>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <easy|normal|hard> | questiontime <sec> | pointsbase <nombre> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <nombre> | keywordslimit <nombre> | rounddelay <ms>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}L'énigme est terminée. La réponse était : {answer}. {explanation}"
    },
    "geo": {
        "startGame": "🎮 Geo-Game lancé !{roundInfo} Devinez le lieu issu du jeu{gameTitleText} ! {durationInfo} Envoyez vos réponses dans le chat ! Premier indice arrive...",
        "startReal": "🌍 Geo-Game lancé !{regionInfo}{roundInfo} Devinez la ville, le monument ou le lieu réel ! {durationInfo} Envoyez vos réponses dans le chat ! Premier indice arrive...",
        "roundInfo": " ({totalRounds} manches)",
        "durationInfo": "Vous avez ⏱️ {roundDurationMinutes} minutes par manche.",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (Région : {regionScope})",
        "nextRound": "🏁 Manche {currentRound}/{totalRounds} commence maintenant ! Bonne chance !",
        "clue": "❓ Indice {clueNumber} : {clueText}",
        "correctGuess": "✅ Bravo @{displayName} ! Tu as trouvé : {locationName}{timeMsg}{streakInfo}{pointsInfo} !",
        "timeout": "⏱️ Temps écoulé ! La bonne réponse était : {locationName}",
        "stopWithAnswer": "🛑 Geo-Game arrêté. La réponse était : {locationName}",
        "stop": "🛑 Geo-Game arrêté.",
        "reveal": "📢 La réponse était : {locationName} ! {revealText}",
        "noScores": "Aucun score enregistré pour cette session.",
        "sessionScores": "Meilleurs joueurs : {list}",
        "gameEndedScores": "🏁 Partie terminée. Scores finaux de la session : {list}",
        "finalScores": "🏁 Scores finaux de la session : {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} a trouvé : {locationName}{timeString}{streakInfo}{pointsInfo} ! ",
            "timeout": "{roundPrefix}⏱️ Temps écoulé ! Le lieu était {locationName}. ",
            "stopped": "{roundPrefix}🛑 Partie arrêtée. Le lieu était {locationName}. ",
            "reveal": "{roundPrefix}📢 La réponse était : {locationName} ! "
        },
        "roundError": "Une erreur est survenue lors de la révélation de la réponse pour la manche {currentRound}.",
        "roundEnded": "La manche est terminée."
    }
};
