// src/locales/fr.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " en {seconds}s",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} pts)",
        "scoreEntry": "{rank}. {name} ({score} pts)",
        "roundText": {
            "one": "une manche",
            "many": "{totalRounds} manches"
        },
        "roundPrefixParen": "(Manche {currentRound}/{totalRounds}) ",
        "justNow": "à l'instant",
        "unknown": "inconnu"
    },
    "trivia": {
        "start": "🎯 Lancement de {roundText} de Trivia ! Thème : {topic}. Vous avez {questionTimeSeconds} secondes pour répondre à chaque question. Tapez vos réponses dans le chat !",
        "roundPrefix": "[Manche {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} TRIVIA : {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} a trouvé{timeString}{streakInfo}{pointsInfo} ! La réponse est : {answer}. {explanation}",
        "timeout": "{roundPrefix}⏱️ Temps écoulé ! La réponse est : {answer}. {explanation}",
        "stop": "{roundPrefix}🛑 Partie arrêtée. La réponse était : {answer}",
        "nextRound": "🎮 Début de la manche {roundNumber} sur {totalRounds}...",
        "noScores": "Aucun score enregistré.",
        "help": {
            "base": "🎮 Commandes Trivia : !trivia (lance une partie de culture générale), !trivia [thème] [manches] (thème précis), !trivia game [manches] (basé sur le jeu du stream), !trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <options...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". Les mods ont accès à des commandes supplémentaires."
        },
        "gameStoppedScores": "🏁 Partie arrêtée. Scores finaux : {list}",
        "finalScores": "🏁 Scores finaux : {list}",
        "NoQuestionEndingGame": "⚠️ Erreur : Impossible de générer une question pour la manche {currentRound}. Fin de la partie.",
        "InvalidQuestionEndingGame": "⚠️ Erreur : La question générée n'était pas valide. Fin de la partie."
    },
    "riddle": {
        "start": "🤔 C'est parti pour {roundText} d'énigmes ! {topicText} Vous avez {questionTimeSeconds} secondes pour répondre. Écrivez vos réponses dans le chat !",
        "topicText": "Thème : {topic}",
        "noTopicText": "J'ai une énigme pour vous !",
        "roundPrefix": "[Énigme {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ ÉNIGME : {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} a trouvé{timeString}{pointsInfo} ! La réponse est : {answer}.{explanationText}",
        "timeout": "{roundPrefix}⏱️ Temps écoulé ! La réponse était : {answer}.{explanationText}",
        "stop": "{roundPrefix}🛑 Partie d'énigmes arrêtée.{explanationText}",
        "stopExplanation": " La réponse était : {answer}. {explanation}",
        "stopAnswerOnly": " La réponse était : {answer}.",
        "noScores": "Aucun score enregistré pour cette session d'énigmes.",
        "sessionScores": "🏁 Meilleurs joueurs de la session d'énigmes : {list}",
        "noLeaderboard": "Aucune stat d'énigmes trouvée pour #{channelName} pour le moment !",
        "leaderboard": "🏆 Maîtres des énigmes sur #{channelName} : {list}",
        "leaderboardEntry": "{rank}. {name} ({points} pts, {solved} résolues)",
        "help": {
            "base": "🤔 Commandes d'énigmes : !riddle (général/partie en cours), !riddle <sujet> [<manches>], !riddle <manches>, !riddle game [<manches>]",
            "common": ", !riddle leaderboard, !riddle report <raison>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <easy|normal|hard> | questiontime <sec> | pointsbase <nombre> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <nombre> | keywordslimit <nombre> | rounddelay <ms>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}L'énigme est terminée. La réponse était : {answer}. {explanation}",
        "NoRiddleThisTime": "Désolé, je n'ai pas réussi à trouver d'énigme cette fois-ci !",
        "StumpedEndingGame": "Je sèche ! Impossible de trouver une nouvelle énigme pour la manche {currentRound}. Fin de la partie."
    },
    "geo": {
        "startGame": "🎮 Geo-Game lancé !{roundInfo} Devinez le lieu issu du jeu{gameTitleText} ! {durationInfo} Envoyez vos réponses dans le chat ! Premier indice arrive...",
        "startReal": "🌍 Geo-Game lancé !{regionInfo}{roundInfo} Devinez la ville, le monument ou le lieu réel ! {durationInfo} Envoyez vos réponses dans le chat ! Premier indice arrive...",
        "roundInfo": " ({totalRounds} manches)",
        "durationInfo": "Vous avez ⏱️ {roundDurationMinutes} minutes par manche.",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (Région : {regionScope})",
        "nextRound": "🏁 Manche {currentRound}/{totalRounds} commence maintenant ! Bonne chance !",
        "clue": "❓ Indice {clueNumber} : {clueText}",
        "correctGuess": "✅ Bravo @{displayName} ! Tu as trouvé : {locationName}{timeMsg}{streakInfo}{pointsInfo} !",
        "timeout": "⏱️ Temps écoulé ! La bonne réponse était : {locationName}",
        "stopWithAnswer": "🛑 Geo-Game arrêté. La réponse était : {locationName}",
        "stop": "🛑 Geo-Game arrêté.",
        "reveal": "📢 La réponse était : {locationName} ! {revealText}",
        "noScores": "Aucun score enregistré pour cette session.",
        "sessionScores": "Meilleurs joueurs : {list}",
        "gameEndedScores": "🏁 Partie terminée. Scores finaux de la session : {list}",
        "finalScores": "🏁 Scores finaux de la session : {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} a trouvé : {locationName}{timeString}{streakInfo}{pointsInfo} ! ",
            "timeout": "{roundPrefix}⏱️ Temps écoulé ! Le lieu était {locationName}. ",
            "stopped": "{roundPrefix}🛑 Partie arrêtée. Le lieu était {locationName}. ",
            "reveal": "{roundPrefix}📢 La réponse était : {locationName} ! "
        },
        "roundError": "Une erreur est survenue lors de la révélation de la réponse pour la manche {currentRound}.",
        "roundEnded": "La manche est terminée.",
        "NoScoresSession": "🏁 Partie terminée. Aucun score enregistré pour cette session.",
        "LeaderboardFetchFailed": "Impossible de récupérer le classement général de la chaîne.",
        "NoLocationEndingGame": "⚠️ Erreur : Impossible de trouver un lieu adapté pour la manche {currentRound}. Fin de la partie.",
        "NoClueEndingGame": "⚠️ Erreur : Impossible de générer un indice pour la manche {currentRound}. Fin de la partie."
    },
    "cmd": {
        "ask": {
            "SorryICouldnT": "Désolé, impossible de trouver ou de générer une réponse pour le moment.",
            "PleaseAskQuestionAfter": "Pose une question après la commande. Utilisation : !ask <ta question>",
            "HeyThereWhatS": "Salut ! De quoi veux-tu parler ?",
            "SorryICouldnT2": "Désolé, impossible de récupérer le contexte actuel."
        },
        "botlang": {
            "BotCurrentlySetSpeak2": "Le bot est actuellement configuré pour parler anglais (par défaut). Utilise \"!botlang <langue>\" pour changer.",
            "BotCurrentlySetSpeak4": "Le bot est actuellement configuré pour parler anglais (par défaut).",
            "BotLanguageHasBeen": "La langue du bot a été réinitialisée en anglais (par défaut).",
            "SorryICouldnT": "Désolé, impossible de traduire en \"{targetLanguage}\". Vérifie le nom de la langue et réessaie.",
            "SorryErrorOccurredWhile": "Désolé, une erreur est survenue lors de la configuration de la langue du bot.",
            "StatusUsageDetected": "Le bot est actuellement configuré pour parler {currentLanguage} (détecté d'après la langue de votre stream Twitch). Utilisez \"!botlang off\" pour réinitialiser en anglais ou \"!botlang <langue>\" pour changer.",
            "StatusUsageSet": "Le bot est actuellement configuré pour parler {currentLanguage}. Utilisez \"!botlang off\" pour réinitialiser en anglais ou \"!botlang <langue>\" pour changer.",
            "StatusDetected": "Le bot est actuellement configuré pour parler {currentLanguage} (détecté d'après la langue de votre stream Twitch).",
            "StatusSet": "Le bot est actuellement configuré pour parler {currentLanguage} (défini par un modérateur)."
        },
        "command": {
            "UsageCommandAddAddai": "Utilisation : !command add/addai/edit/remove/show/options <nom> [réponse/options]",
            "UnknownSubcommandUseAdd": "Sous-commande \"{subCommand}\" inconnue. Utilise add, addai, edit, remove, show ou options.",
            "PleaseSpecifyCommandName": "Précise un nom de commande. Utilisation : !command {p1} <nom> <réponse>",
            "PleaseSpecifyResponseUsage": "Précise une réponse. Utilisation : !command {p1} {commandName} <réponse>",
            "CommandHasBeenAdded": "La commande !{commandName} a été ajoutée {p2}.",
            "CommandAlreadyExistsUse": "La commande !{commandName} existe déjà. Utilise \"!command edit\" pour la modifier.",
            "ErrorAddingCommandPlease": "Erreur lors de l'ajout de la commande. Réessaie plus tard.",
            "PleaseSpecifyCommandName2": "Précise un nom de commande. Utilisation : !command edit <nom> <réponse>",
            "PleaseSpecifyNewResponse": "Précise une nouvelle réponse. Utilisation : !command edit {commandName} <réponse>",
            "CommandHasBeenUpdated": "La commande !{commandName} a été mise à jour.",
            "CommandNotFoundUse": "Commande !{commandName} introuvable. Utilise \"!command add\" pour la créer.",
            "ErrorEditingCommandPlease": "Erreur lors de la modification de la commande. Réessaie plus tard.",
            "PleaseSpecifyCommandName3": "Précise un nom de commande. Utilisation : !command remove <nom>",
            "CommandHasBeenRemoved": "La commande !{commandName} a été supprimée.",
            "CommandNotFound": "Commande !{commandName} introuvable.",
            "ErrorRemovingCommandPlease": "Erreur lors de la suppression de la commande. Réessaie plus tard.",
            "PleaseSpecifyCommandName4": "Précise un nom de commande. Utilisation : !command show <nom>",
            "ErrorFetchingCommandPlease": "Erreur lors de la récupération de la commande. Réessaie plus tard.",
            "UsageCommandOptionsName": "Utilisation : !command options <nom> <clé>=<valeur>",
            "UsageCommandOptionsPermission": "Utilisation : !command options {commandName} permission=moderator ou cooldown=30",
            "InvalidPermissionValidOptions": "Permission invalide. Options valides : {p1}",
            "CooldownMustNonNegative": "Le cooldown doit être un nombre positif ou nul (en secondes).",
            "InvalidTypeValidOptions": "Type invalide. Options valides : text, prompt",
            "UnknownOptionAvailablePermission": "Option inconnue \"{key}\". Disponibles : permission, cooldown, type",
            "NoValidOptionsProvided": "Aucune option valide fournie.",
            "OptionsUpdated": "Options de !{commandName} mises à jour : {changes}",
            "ErrorUpdatingOptionsPlease": "Erreur lors de la mise à jour des options. Réessaie plus tard."
        },
        "disable": {
            "UsageDisableCommandnameExample": "Utilisation : !disable <nomCommande>. Exemple : !disable trivia",
            "UnknownCommandAvailableCommands": "Commande '{commandToDisable}' inconnue. Commandes disponibles : {p2}",
            "SorryThereWasError": "Désolé, une erreur s'est produite lors de la désactivation de la commande. Réessaie plus tard."
        },
        "enable": {
            "UsageEnableCommandnameExample": "Utilisation : !enable <nomCommande>. Exemple : !enable trivia",
            "UnknownCommandAvailableCommands": "Commande inconnue '{commandToEnable}'. Commandes disponibles : {p2}",
            "SorryThereWasError": "Désolé, une erreur s'est produite lors de l'activation de la commande. Réessaie plus tard."
        },
        "followage": {
            "SorryFollowageDataCurrently": "Désolé, les données de followage sont actuellement indisponibles. Le diffuseur doit peut-être se réauthentifier.",
            "SorryCouldnTDetermine": "Désolé, impossible de déterminer l'ID du diffuseur.",
            "UserNotFound": "Utilisateur \"{targetUsername}\" introuvable.",
            "HaveBeenFollowing": "{displayName}, tu suis {p2} depuis {duration} !",
            "HasBeenFollowing": "{targetDisplayName} suit {p2} depuis {duration} !",
            "AreNotFollowing": "{displayName}, tu ne suis pas {p2}.",
            "NotFollowing": "{targetDisplayName} ne suit pas {p2}.",
            "SorryThereWasError": "Désolé, une erreur est survenue lors de la vérification du followage. Réessaie plus tard."
        },
        "game": {
            "IDonTSee": "Je ne vois aucun jeu configuré pour le stream actuellement.",
            "SorryErrorOccurredWhile": "Désolé, une erreur s'est produite lors du traitement de la commande !game.",
            "CouldnTDetermineCurrent": "Impossible de déterminer le jeu actuel. La chaîne ne diffuse peut-être pas de jeu.",
            "CouldnTFetchStream": "Impossible de récupérer la miniature du stream. La chaîne est peut-être hors ligne.",
            "AiCouldnTAnalyze": "L'AI n'a pas pu analyser le gameplay de {officialGameName} initialement.",
            "SorryThereWasError": "Désolé, une erreur est survenue lors de l'analyse du stream.",
            "ICouldnTDetermine": "Je n'ai pas pu déterminer le jeu actuel.",
            "CurrentlyPlayingTryGame": "Joue actuellement à {gameName}. Essaie \"!game [ta question]\" pour de l'aide spécifique sur le jeu.",
            "CurrentGame": "Jeu actuel : {gameName}",
            "IMFetchingCurrent": "Je récupère les infos du jeu actuel. Réessaie \"!game {helpQuery}\" dans quelques secondes, ou précise le nom du jeu : \"!search <jeu> {helpQuery}\".",
            "SorryICouldnT": "Désolé, impossible de trouver de l'aide pour \"{helpQuery}\" dans {gameName} pour l'instant.",
            "SorryErrorOccurredWhile2": "Désolé, une erreur est survenue lors de la recherche d'aide pour \"{helpQuery}\".",
            "LeaderboardFetchFailed": "Désolé, impossible de récupérer le classement pour le moment.",
            "ClearLeaderboardFailed": "Une erreur inattendue est survenue en essayant d'effacer le classement.",
            "ResetConfigFailed": "Une erreur inattendue est survenue lors de la réinitialisation de la configuration.",
            "ReportFailed": "Une erreur est survenue lors de l'initialisation du signalement.",
            "StreamGameFetchFailed": "Erreur lors de la récupération du jeu actuel du stream.",
            "StartGameFailed": "Une erreur inattendue est survenue en essayant de lancer la partie."
        },
        "gameHandlerUtils": {
            "ThereNoActiveStop": "Aucune partie de {gameName} en cours à arrêter.",
            "OnlyGameInitiatorMods": "Seuls l'initiateur de la partie, les mods ou le diffuseur peuvent arrêter la partie en cours.",
            "OnlyModsOrBroadcaster": "Seuls les mods ou le diffuseur peuvent effacer le classement.",
            "AttemptingClearLeaderboardData": "Tentative d'effacement du classement de {gameName} pour cette chaîne. Cela peut prendre un moment...",
            "OnlyModsOrBroadcaster2": "Seuls les mods ou le diffuseur peuvent réinitialiser la configuration du jeu.",
            "PleaseProvideReasonReporting": "Merci d'indiquer une raison pour le signalement. Utilisation : !{commandName} report <ta raison>",
            "CouldNotProcessReport": "Impossible de traiter ta demande de signalement pour le moment.",
            "OnlyModsOrBroadcaster3": "Seuls les mods ou le diffuseur peuvent configurer le jeu.",
            "MaximumNumberRoundsStarting": "Le nombre maximum de manches est de {maxRounds}. Lancement d'une partie en {maxRounds} manches."
        },
        "geo": {
            "CouldNotDetectCurrent": "Impossible de détecter le jeu actuel. Merci d'en préciser un : !geo game <Titre du jeu> [manches]",
            "GeoGameGeoRegion": "Géo-Jeu : !geo [région] [manches] (démarrer réel), !geo game [Titre] [manches] (démarrer jeu), !geo stop (mods/initiateur), !geo config <opts...> (mods), !geo resetconfig (mods), !geo leaderboard, !geo clearleaderboard (mods), !geo report <raison...>, !geo help",
            "UnknownCommandFormatOr": "Format de commande inconnu ou arguments en trop. Utilise !geo help."
        },
        "quote": {
            "NoQuotesYetAdd": "Aucune citation pour l'instant. Ajoutes-en une avec \"!quote add <texte [- auteur]>\"",
            "QuoteNotFound": "Citation #{id} introuvable.",
            "NoQuotesYet": "Aucune citation pour le moment.",
            "UsageQuoteSearchTerm": "Utilisation : !quote search <terme>",
            "NoQuotesMatching": "Aucune citation correspondant à \"{term}\".",
            "UsageQuoteQuote12": "Utilisation : !quote | !quote 12 | !quote add <texte [- auteur]> | !quote last | !quote search <terme> | !quote delete <id> | !quote edit <id> <texte>",
            "UsageQuoteAddText": "Utilisation : !quote add <texte [- auteur]>",
            "QuoteTooLongMax": "Citation trop longue ({MAX_QUOTE_LENGTH} car. max).",
            "AddedQuote": "Citation #{quoteId} ajoutée : \"{text}\"{suffix}",
            "OnlyModsBroadcasterCan": "Seuls les modos/le diffuseur peuvent supprimer des citations.",
            "UsageQuoteDeleteId": "Utilisation : !quote delete <id>",
            "OnlyModsBroadcasterCan2": "Seuls les modos/le diffuseur peuvent modifier des citations.",
            "UsageQuoteEditId": "Utilisation : !quote edit <id> <texte [- auteur]>",
            "SorrySomethingWentWrong": "Désolé, une erreur est survenue lors du traitement de !quote."
        },
        "riddle": {
            "OnlyGameInitiatorMods": "Seul l'initiateur du jeu, les modos ou le diffuseur peuvent arrêter l'énigme.",
            "ICanTStop": "Je ne peux pas m'arrêter !"
        },
        "search": {
            "PleaseProvideSomethingSearch": "Indiquez un terme à rechercher. Utilisation : !search <votre recherche>",
            "SorryICouldnT": "Désolé, impossible de récupérer le contexte actuel pour effectuer la recherche.",
            "SorryICouldnT2": "Désolé, impossible de trouver des infos sur \"{userQuery}\" pour le moment.",
            "SorryErrorOccurredWhile": "Désolé, une erreur est survenue lors de la recherche."
        },
        "timer": {
            "UsageTimerAddAddai": "Utilisation : !timer add/addai/edit/interval/lines/enable/disable/remove/show/list <nom> [...]",
            "UnknownSubcommandUseAdd": "Sous-commande \"{subCommand}\" inconnue. Utilisez add, addai, edit, interval, lines, enable, disable, remove, show ou list.",
            "PleaseSpecifyTimerName": "Veuillez spécifier un nom de timer. {usage}",
            "TimerNameSanitizedNothing": "Nom de timer vide après nettoyage — essayez avec des lettres ou des chiffres.",
            "ReservedWordCanT": "\"{timerName}\" est un mot réservé et ne peut pas être utilisé comme nom de timer.",
            "PleaseSpecifyIntervalBetween": "Précise un intervalle entre {MIN_INTERVAL_MINUTES} et {MAX_INTERVAL_MINUTES} minutes. {usage}",
            "TimerTextMustCharacters": "Le texte du timer doit faire {MAX_RESPONSE_LENGTH} caractères ou moins.",
            "TimersFireWithoutTriggering": "Les timers se déclenchent sans utilisateur, donc ces variables ne sont pas prises en charge : {p1}",
            "TimerAddedFiresEvery": "Timer \"{timerName}\" ajouté{p2} — se déclenche toutes les {intervalMinutes}m quand le stream est en direct et le chat actif.",
            "TimerAlreadyExistsUse": "Le timer \"{timerName}\" existe déjà. Utilise \"!timer edit\" pour le modifier.",
            "PleaseSpecifyTimerName2": "Précise un nom de timer. Utilisation : !timer edit <nom> <message>",
            "PleaseSpecifyNewText": "Précise le nouveau texte. Utilisation : !timer edit {timerName} <message>",
            "TimerNotFoundUse": "Timer \"{timerName}\" introuvable. Utilise \"!timer add\" pour le créer.",
            "TimerHasBeenUpdated": "Le timer \"{timerName}\" a été mis à jour.",
            "ErrorEditingTimerPlease": "Erreur lors de la modification du timer. Réessaie plus tard.",
            "UsageTimerIntervalName": "Utilisation : !timer interval <nom> <minutes>",
            "IntervalMustBetweenMinutes": "L'intervalle doit être compris entre {MIN_INTERVAL_MINUTES} et {MAX_INTERVAL_MINUTES} minutes.",
            "TimerNowFiresEvery": "Le timer \"{timerName}\" se déclenche désormais toutes les {intervalMinutes}m.",
            "TimerNotFound": "Timer \"{timerName}\" introuvable.",
            "ErrorUpdatingTimerPlease": "Erreur lors de la mise à jour du timer. Réessaie plus tard.",
            "UsageTimerLinesName": "Utilisation : !timer lines <nom> <nombre>",
            "ChatLinesMustBetween": "Les lignes de chat doivent être comprises entre 0 et {MAX_MIN_CHAT_LINES}.",
            "UsageTimerName": "Utilisation : !timer {p1} <nom>",
            "PleaseSpecifyTimerName3": "Précise un nom de timer. Utilisation : !timer remove <nom>",
            "TimerHasBeenRemoved": "Le timer \"{timerName}\" a été supprimé.",
            "ErrorRemovingTimerPlease": "Erreur lors de la suppression du timer. Réessaie plus tard.",
            "PleaseSpecifyTimerName4": "Précise un nom de timer. Utilisation : !timer show <nom>",
            "TimerEveryMMin": "Timer \"{timerName}\"{typeInfo}{statusInfo} — toutes les {intervalMinutes}m, min {minChatLines} lignes : {response}",
            "ErrorFetchingTimerPlease": "Erreur lors de la récupération du timer. Réessaie plus tard.",
            "NoTimersConfiguredUse": "Aucun timer configuré. Utilise \"!timer add <nom> <minutes> <message>\" pour en créer un.",
            "Timers": "Timers ({length}) : {summary}",
            "ErrorListingTimersPlease": "Erreur lors de l'affichage des timers. Réessaie plus tard.",
            "PleaseSpecifyPrompt": "Précise un prompt. {usage}",
            "PleaseSpecifyMessage": "Précise un message. {usage}",
            "TimerEnabled": "Le timer \"{timerName}\" a été activé.",
            "TimerDisabled": "Le timer \"{timerName}\" a été désactivé."
        },
        "translate": {
            "UsageTranslateLanguageUser": "Utilisation : !translate <langue> [utilisateur] | !translate stop [utilisateur|all]",
            "OnlyModsOrBroadcaster": "Seuls les modérateurs ou le diffuseur peuvent arrêter toutes les traductions.",
            "OkayStoppedTranslationsGlobally": "C'est fait, traductions arrêtées globalement pour {count} utilisateur(s).",
            "SorryErrorOccurredTrying": "Désolé, une erreur est survenue lors de l'arrêt de toutes les traductions.",
            "OnlyModsOrBroadcaster2": "Seuls les modérateurs ou le diffuseur peuvent gérer les traductions pour les autres utilisateurs.",
            "PleaseSpecifyLanguageExample": "Précise une langue. Exemple : !translate spanish",
            "SorryErrorOccurredWhile": "Désolé, une erreur est survenue lors de l'exécution de la commande de traduction."
        },
        "commandProcessor": {
            "OopsSomethingWentWrong": "Oups ! Une erreur est survenue lors de l'exécution de !{command}."
        },
        "messageHandlers": {
            "OkayStoppedTranslationsGlobally": "C'est bon, traductions arrêtées globalement pour {count} utilisateur(s).",
            "OnlyModsBroadcasterCan": "Seuls les modos/le streamer peuvent arrêter la traduction pour les autres."
        }
    },
    "result": {
        "trivia": {
            "NoActiveTriviaGame": "Aucune partie de Trivia en cours à arrêter.",
            "TriviaGameStoppedSuccessfully": "Partie de Trivia arrêtée avec succès.",
            "TriviaSettingsUpdated": "Paramètres du Trivia mis à jour : {p1}.",
            "SettingsUpdatedMemoryBut": "Paramètres mis à jour en mémoire, mais échec de l'enregistrement permanent.",
            "TriviaSettingsNotChanged": "Paramètres du Trivia inchangés : {p1}.",
            "NoValidConfigurationOptions": "Aucune option de configuration valide. Utilisez !trivia help config pour voir les options.",
            "TriviaConfigurationResetDefaults": "Configuration du Trivia réinitialisée par défaut.",
            "ConfigurationResetMemoryBut": "Configuration réinitialisée en mémoire, mais échec de l'enregistrement permanent.",
            "ErrorOccurred": "Une erreur est survenue : {p1}",
            "ICouldnTFind": "Impossible de trouver une manche de Trivia récente à signaler sur cette chaîne.",
            "CouldNotIdentifySpecific": "Impossible d'identifier une question précise à signaler de la dernière partie.",
            "ThanksFeedbackQuestionHas": "Merci pour le retour ! La question (\"{p1}...\") a bien été signalée.",
            "SorryErrorOccurredWhile": "Désolé, une erreur est survenue lors du signalement de la question.",
            "NoSpecificQuestionsFound": "Aucune question trouvée à signaler dans la dernière session de jeu.",
            "ReportSessionTimedOut": "@{username}, la session de signalement a expiré. Veuillez réutiliser !trivia report.",
            "SNotValidRound": "@{username}, ce n'est pas un numéro de manche valide (1-{maxRound}) de la dernière partie. Répondez avec un numéro valide ou relancez le signalement.",
            "IFoundRoundBut": "@{username}, manche {roundNum} trouvée, mais impossible d'identifier la question à signaler. Merci de réessayer.",
            "ThanksReportQuestionFrom": "@{username}, merci ! Votre signalement pour la question de la manche {roundNum} (\"{p3}...\") a bien été envoyé.",
            "ErrorOccurredSubmittingReport": "@{username}, une erreur est survenue lors de l'envoi de ton signalement pour la manche {roundNum}. Réessaie ou contacte un modo.",
            "ErrRoundGameInitiatedBy": "Une partie en {totalRounds} manches lancée par toi est déjà en cours (manche {currentRound}). Utilise !trivia stop si besoin.",
            "ErrGameAlreadyActivePlease": "Une partie est déjà en cours ({state}). Patiente ou utilise !trivia stop.",
            "ErrErrorStartingGame": "Erreur lors du lancement de la partie : {p1}"
        },
        "geo": {
            "NoActiveGeoGame": "Aucune manche/session de Geo-Game active à arrêter sur cette chaîne.",
            "GeoGameStoppedSuccessfully": "Geo-Game arrêté avec succès. Affichage des résultats finaux (s'il y en a) en cours.",
            "GeoGameSettingsUpdated": "Paramètres de Geo-Game mis à jour : {p1}.",
            "SettingsUpdatedMemoryBut": "Paramètres mis à jour en mémoire, mais échec de la sauvegarde permanente.",
            "GeoGameSettingsNot": "Paramètres de Geo-Game inchangés : {p1}.",
            "NoValidConfigurationOptions": "Aucune option de configuration valide fournie ou paramètres déjà à jour. Utilise !geo help config pour voir les options.",
            "GeoGameConfigurationReset": "Configuration de Geo-Game réinitialisée par défaut.",
            "ConfigurationResetMemoryBut": "Configuration réinitialisée en mémoire, mais échec de la sauvegarde permanente. Merci de réessayer.",
            "ICouldnTFind": "Impossible de trouver une manche récente de Geo-Game à signaler sur cette chaîne.",
            "CouldNotIdentifySpecific": "Impossible d'identifier un lieu précis à signaler pour la dernière partie.",
            "SorryErrorOccurredWhile": "Désolé, une erreur est survenue lors de la tentative de signalement du lieu.",
            "NoSpecificLocationsFound": "Aucun lieu précis trouvé à signaler dans la dernière session de jeu.",
            "ReportSessionTimedOut": "@{username}, le délai pour ton signalement a expiré. Merci d'utiliser à nouveau !geo report.",
            "SNotValidRound": "@{username}, ce n'est pas un numéro de manche valide (1-{maxRound}) pour la dernière session. Réponds avec un numéro valide ou réessaie de signaler.",
            "IFoundRoundBut": "@{username}, j'ai bien trouvé la manche {roundNum}, mais un problème est survenu lors de son identification pour le rapport. Merci de réessayer.",
            "ThanksReportLocationFrom": "@{username}, merci ! Ton signalement pour le lieu de la manche {roundNum} (\"{p3}...\") a bien été envoyé.",
            "ErrorOccurredSubmittingReport": "@{username}, une erreur est survenue lors de l'envoi de ton signalement pour la manche {roundNum}. Réessaie ou contacte un modo.",
            "ErrRoundGameInitiatedBy": "Une partie en {totalRounds} manches lancée par toi est déjà en cours (actuellement manche {currentRound}). Utilise !geo stop si besoin.",
            "ErrGameAlreadyActiveOr": "Une partie est déjà en cours ou se termine ({state}). Patiente ou utilise !geo stop.",
            "ErrGameStoppedBeforeFirst": "La partie a été arrêtée avant le premier indice."
        },
        "riddle": {
            "NoActiveRiddleGame": "Aucune énigme active à arrêter.",
            "RiddleGameBeingStopped": "Arrêt du jeu d'énigme en cours.",
            "RiddleSettingsUpdated": "Paramètres des énigmes mis à jour : {p1}.",
            "SettingsChangedMemoryBut": "Paramètres modifiés en mémoire mais échec de la sauvegarde.",
            "RiddleGameConfigurationReset": "Configuration du jeu d'énigmes réinitialisée par défaut.",
            "ConfigResetMemoryBut": "Configuration réinitialisée en mémoire mais échec de la sauvegarde.",
            "ICouldnTFind": "Impossible de trouver une énigme récente dans cette chaîne à signaler.",
            "LastRiddleFoundSeems": "La dernière énigme trouvée semble incomplète et ne peut pas être signalée.",
            "ThanksFeedbackRiddleStarting": "Merci pour le retour ! L'énigme commençant par \"{p1}...\" a été signalée.",
            "SorryErrorOccurredWhile": "Désolé, une erreur s'est produite lors du signalement de l'énigme.",
            "ICouldnTFind2": "Impossible de trouver des énigmes récentes dans cette chaîne à signaler.",
            "CouldNotIdentifySpecific": "Impossible d'identifier une énigme précise à signaler.",
            "ThanksFeedbackRiddleHas": "Merci pour le retour ! L'énigme (\"{p1}...\") a été signalée.",
            "SorryErrorOccurredWhile2": "Désolé, une erreur s'est produite lors du signalement de l'énigme.",
            "SNotValidRound": "@{username}, ce n'est pas un numéro de manche valide (1-{length}). Réessaie de signaler.",
            "ICouldnTFind3": "@{username}, impossible de trouver l'énigme de la manche {roundNum}. Réessaie de signaler.",
            "ThanksReportRiddleFrom": "@{username}, merci ! Ton signalement pour l'énigme de la manche {roundNum} (\"{p3}...\") a été envoyé.",
            "ErrorOccurredSubmittingReport": "@{username}, une erreur s'est produite lors de l'envoi de ton signalement pour la manche {roundNum}. Réessaie.",
            "ErrFailedStartRiddleGame": "Impossible de lancer le jeu d'énigmes. Impossible de générer la première énigme.",
            "RiddleSettingsUnchanged": "Paramètres des énigmes : {p1}.",
            "NoValidRiddleSettings": "Aucun paramètre d'énigme valide n'a été modifié."
        },
        "commandState": {
            "CommandAlwaysAvailableCannot": "La commande '{normalizedCommand}' est toujours disponible et ne peut pas être désactivée.",
            "ErrorDisablingCommandPlease": "Erreur lors de la désactivation de la commande '!{commandName}'. Réessaie.",
            "ErrorEnablingCommandPlease": "Erreur lors de l'activation de la commande '!{commandName}'. Réessaie."
        }
    },
    "change": {
        "trivia": {
            "Difficulty": "Difficulté définie sur {difficulty}",
            "QuestionTimeSeconds": "Temps par question défini sur {time} secondes",
            "InvalidQuestionTimeMust": "Temps par question invalide \"{questionTimeSeconds}\". Doit être compris entre 10 et 120 secondes.",
            "RoundDurationMinutes": "Durée de la manche définie sur {duration} minutes",
            "InvalidRoundDurationMust": "Durée de manche invalide \"{roundDurationMinutes}\". Doit être comprise entre 1 et 10 minutes.",
            "TopicPreferencesUpdated": "Préférences de thèmes mises à jour : {p1}",
            "BasePoints": "Points de base définis sur {points}",
            "InvalidBasePointsMust": "Points de base invalides \"{pointsBase}\". Doit être compris entre 1 et 100.",
            "ScoreTrackingEnabled": "Suivi des scores activé",
            "ScoreTrackingDisabled": "Suivi des scores désactivé",
            "TimeBonusEnabled": "Bonus de temps activé",
            "TimeBonusDisabled": "Bonus de temps désactivé",
            "DifficultyMultiplierEnabled": "Multiplicateur de difficulté activé",
            "DifficultyMultiplierDisabled": "Multiplicateur de difficulté désactivé"
        },
        "geo": {
            "Difficulty": "Difficulté définie sur {difficulty}",
            "ClueIntervalSeconds": "Intervalle des indices défini sur {interval} secondes",
            "InvalidClueIntervalMust": "Intervalle d'indices invalide \"{clueIntervalSeconds}\". Doit être compris entre 30 et 300.",
            "RoundDurationMinutes": "Durée de la manche définie sur {duration} minutes",
            "InvalidRoundDurationMust": "Durée de manche invalide \"{roundDurationMinutes}\". Doit être comprise entre 3 et 20 minutes.",
            "RegionRestrictionsUpdated": "Restrictions régionales mises à jour : {p1}",
            "GameTitlePreferencesUpdated": "Préférences de titres de jeux mises à jour : {p1}",
            "BasePoints": "Points de base définis sur {points}",
            "InvalidBasePointsMust": "Points de base invalides \"{pointsBase}\". Doit être compris entre 1 et 100.",
            "ScoreTrackingEnabled": "Suivi des scores activé",
            "ScoreTrackingDisabled": "Suivi des scores désactivé",
            "TimeBonusScoringEnabled": "Calcul du bonus de temps activé",
            "TimeBonusScoringDisabled": "Calcul du bonus de temps désactivé",
            "DifficultyMultiplierScoringEnabled": "Calcul du multiplicateur de difficulté activé",
            "DifficultyMultiplierScoringDisabled": "Calcul du multiplicateur de difficulté désactivé"
        },
        "riddle": {
            "Difficulty": "Difficulté définie sur {difficulty}",
            "QuestionTimeS": "Temps par question défini sur {time}s",
            "InvalidQuestionTime15": "Temps par question invalide (15-120s)",
            "Invalid": "{optionName} non valide ({min}-{max})",
            "BasePoints": "Points de base définis sur {value}",
            "MaxRounds": "Manches max définies sur {value}",
            "KeywordLimit": "Limite d'exclusion de mots-clés définie sur {value}",
            "RoundDelay": "Délai de manche défini sur {value}ms",
            "ScoreTrackingEnabled": "Suivi des scores activé",
            "ScoreTrackingDisabled": "Suivi des scores désactivé",
            "TimeBonusEnabled": "Bonus de temps activé",
            "TimeBonusDisabled": "Bonus de temps désactivé",
            "DifficultyMultiplierEnabled": "Multiplicateur de difficulté activé",
            "DifficultyMultiplierDisabled": "Multiplicateur de difficulté désactivé"
        },
        "common": {
            "None": "Aucun"
        }
    },
    "usage": {
        "riddle": {
            "Config": "Utilisation : !riddle config difficulty <facile|normal|difficile> | questiontime <sec> | pointsbase <num> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <num> | keywordslimit <num> | rounddelay <ms>"
        },
        "trivia": {
            "Config": "Utilisation : !trivia config difficulty <facile|normal|difficile> time <secondes> duration <minutes> topic <liste> scoring <true|false> points <valeur> timebonus <true|false> difficultymultiplier <true|false>"
        },
        "geo": {
            "Config": "Utilisation : !geo config difficulty <facile|normal|difficile> interval <sec> duration <min> region <liste> game <liste> scoring <bool> points <num> timebonus <bool> difficultymultiplier <bool>"
        }
    }
};
