// src/locales/it.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " in {seconds}s",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} pt)",
        "scoreEntry": "{rank}. {name} ({score} pt)",
        "roundText": {
            "one": "un round",
            "many": "{totalRounds} round"
        },
        "roundPrefixParen": "(Round {currentRound}/{totalRounds}) "
    },
    "trivia": {
        "start": "🎯 Inizia {roundText} di Trivia! Argomento: {topic}. Avete {questionTimeSeconds} secondi per rispondere a ogni domanda. Scrivete le risposte in chat!",
        "roundPrefix": "[Round {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} TRIVIA: {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} ha indovinato{timeString}{streakInfo}{pointsInfo}! La risposta è: {answer}. {explanation}",
        "timeout": "{roundPrefix}⏱️ Tempo scaduto! La risposta è: {answer}. {explanation}",
        "stop": "{roundPrefix}🛑 Gioco interrotto. La risposta era: {answer}",
        "nextRound": "🎮 Inizia il Round {roundNumber} di {totalRounds}...",
        "noScores": "Nessun punteggio registrato.",
        "help": {
            "base": "🎮 Comandi Trivia: !trivia (avvia una partita di cultura generale), !trivia [topic] [rounds] (argomento specifico), !trivia game [rounds] (basato sul gioco dello stream), !trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <opzioni...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". I mod possono usare comandi aggiuntivi."
        },
        "gameStoppedScores": "🏁 Gioco interrotto. Punteggi finali: {list}",
        "finalScores": "🏁 Punteggi finali: {list}"
    },
    "riddle": {
        "start": "🤔 Inizia {roundText} di Indovinelli! {topicText} Avete {questionTimeSeconds} secondi per rispondere. Scrivete le vostre risposte in chat!",
        "topicText": "Argomento: {topic}",
        "noTopicText": "Ho un indovinello per voi!",
        "roundPrefix": "[Indovinello {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ INDOVINELLO: {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} l'ha indovinato{timeString}{pointsInfo}! La risposta è: {answer}.{explanationText}",
        "timeout": "{roundPrefix}⏱️ Tempo scaduto! La risposta era: {answer}.{explanationText}",
        "stop": "{roundPrefix}🛑 Gioco degli indovinelli interrotto.{explanationText}",
        "stopExplanation": " La risposta era: {answer}. {explanation}",
        "stopAnswerOnly": " La risposta era: {answer}.",
        "noScores": "Nessun punteggio registrato per questa sessione di indovinelli.",
        "sessionScores": "🏁 Top Player della sessione di Indovinelli: {list}",
        "noLeaderboard": "Nessuna statistica degli Indovinelli trovata per #{channelName}!",
        "leaderboard": "🏆 Campioni degli Indovinelli in #{channelName}: {list}",
        "leaderboardEntry": "{rank}. {name} ({points} pt, {solved} risolti)",
        "help": {
            "base": "🤔 Comandi Indovinelli: !riddle (generale/partita in corso), !riddle <argomento> [<round>], !riddle <round>, !riddle game [<round>]",
            "common": ", !riddle leaderboard, !riddle report <motivo>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <easy|normal|hard> | questiontime <sec> | pointsbase <num> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <num> | keywordslimit <num> | rounddelay <ms>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}L'indovinello è finito. La risposta era: {answer}. {explanation}"
    },
    "geo": {
        "startGame": "🎮 Geo-Game iniziato!{roundInfo} Indovina il luogo del gioco{gameTitleText}! {durationInfo} Scrivi le tue risposte in chat! Arriva il primo indizio...",
        "startReal": "🌍 Geo-Game iniziato!{regionInfo}{roundInfo} Indovina la città, il monumento o il luogo reale! {durationInfo} Scrivi le tue risposte in chat! Arriva il primo indizio...",
        "roundInfo": " ({totalRounds} round)",
        "durationInfo": "Hai ⏱️ {roundDurationMinutes} minuti per round.",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (Regione: {regionScope})",
        "nextRound": "🏁 Round {currentRound}/{totalRounds} al via! Buona fortuna!",
        "clue": "❓ Indizio {clueNumber}: {clueText}",
        "correctGuess": "✅ Complimenti @{displayName}! Hai indovinato: {locationName}{timeMsg}{streakInfo}{pointsInfo}!",
        "timeout": "⏱️ Tempo scaduto! La risposta corretta era: {locationName}",
        "stopWithAnswer": "🛑 Geo-Game interrotto. La risposta era: {locationName}",
        "stop": "🛑 Geo-Game interrotto.",
        "reveal": "📢 La risposta era: {locationName}! {revealText}",
        "noScores": "Nessun punteggio registrato per questa sessione.",
        "sessionScores": "Migliori giocatori: {list}",
        "gameEndedScores": "🏁 Partita terminata. Punteggi finali della sessione: {list}",
        "finalScores": "🏁 Punteggi finali della sessione: {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} ha indovinato: {locationName}{timeString}{streakInfo}{pointsInfo}! ",
            "timeout": "{roundPrefix}⏱️ Tempo scaduto! Il luogo era {locationName}. ",
            "stopped": "{roundPrefix}🛑 Gioco interrotto. Il luogo era {locationName}. ",
            "reveal": "{roundPrefix}📢 La risposta era: {locationName}! "
        },
        "roundError": "Si è verificato un errore nel rivelare la risposta per il round {currentRound}.",
        "roundEnded": "Il round è terminato."
    }
};
