// src/locales/ja.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " ({seconds}秒)",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} pts)",
        "scoreEntry": "{rank}. {name} ({score} pts)",
        "roundText": {
            "one": "1ラウンド",
            "many": "{totalRounds}ラウンド"
        },
        "roundPrefixParen": "(ラウンド {currentRound}/{totalRounds}) "
    },
    "trivia": {
        "start": "🎯 トリビア（{roundText}）スタート！トピック: {topic}。回答時間は各問{questionTimeSeconds}秒。チャットで答えを入力してね！",
        "roundPrefix": "[ラウンド {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} トリビア: {question} ({timeSeconds}秒)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} 正解{timeString}{streakInfo}{pointsInfo}！正解は「{answer}」。{explanation}",
        "timeout": "{roundPrefix}⏱️ 時間切れ！正解は「{answer}」。{explanation}",
        "stop": "{roundPrefix}🛑 ゲームを終了しました。正解は「{answer}」でした",
        "nextRound": "🎮 ラウンド {roundNumber}/{totalRounds} を開始中...",
        "noScores": "記録されたスコアはありません。",
        "help": {
            "base": "🎮 トリビアコマンド: !trivia (一般知識クイズ開始)、!trivia [トピック] [ラウンド数] (特定トピック)、!trivia game [ラウンド数] (配信中のゲーム連動)、!trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <オプション...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". モデレーター用コマンドもあります。"
        },
        "gameStoppedScores": "🏁 ゲームを終了しました。最終スコア: {list}",
        "finalScores": "🏁 最終スコア: {list}"
    },
    "riddle": {
        "start": "🤔 なぞなぞ{roundText}をスタート！ {topicText} 制限時間は{questionTimeSeconds}秒。チャットで回答してね！",
        "topicText": "お題: {topic}",
        "noTopicText": "なぞなぞを出すよ！",
        "roundPrefix": "[なぞなぞ {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ 問題: {question} ({timeSeconds}秒)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} が正解{timeString}{pointsInfo}！ 答えは「{answer}」でした。{explanationText}",
        "timeout": "{roundPrefix}⏱️ タイムアップ！ 正解は「{answer}」でした。{explanationText}",
        "stop": "{roundPrefix}🛑 なぞなぞを終了しました。{explanationText}",
        "stopExplanation": " 正解は「{answer}」でした。{explanation}",
        "stopAnswerOnly": " 正解は「{answer}」でした。",
        "noScores": "このセッションのスコア記録はありません。",
        "sessionScores": "🏁 なぞなぞセッション トッププレイヤー: {list}",
        "noLeaderboard": "#{channelName} のなぞなぞ記録はまだありません！",
        "leaderboard": "🏆 #{channelName} のなぞなぞマスター: {list}",
        "leaderboardEntry": "{rank}位. {name} ({points}pt, 正解数:{solved})",
        "help": {
            "base": "🤔 なぞなぞコマンド: !riddle (通常/進行中のゲーム), !riddle <お題> [<ラウンド数>], !riddle <ラウンド数>, !riddle game [<ラウンド数>]",
            "common": ", !riddle leaderboard, !riddle report <理由>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <easy|normal|hard> | questiontime <秒> | pointsbase <数値> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <数値> | keywordslimit <数値> | rounddelay <ミリ秒>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}なぞなぞ終了！正解は: {answer} でした。{explanation}"
    },
    "geo": {
        "startGame": "🎮 ジオゲーム開始！{roundInfo} ゲーム{gameTitleText}の場所を当てよう！ {durationInfo} チャットに予想を書いてね！最初のヒントが来るよ...",
        "startReal": "🌍 ジオゲーム開始！{regionInfo}{roundInfo} 実在する都市、名所、場所を当てよう！ {durationInfo} チャットに予想を書いてね！最初のヒントが来るよ...",
        "roundInfo": " ({totalRounds}ラウンド)",
        "durationInfo": "制限時間は1ラウンドにつき ⏱️ {roundDurationMinutes}分です。",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (対象地域: {regionScope})",
        "nextRound": "🏁 ラウンド {currentRound}/{totalRounds} スタート！みんな頑張って！",
        "clue": "❓ ヒント {clueNumber}: {clueText}",
        "correctGuess": "✅ おめでとう @{displayName}！正解: {locationName}{timeMsg}{streakInfo}{pointsInfo}！",
        "timeout": "⏱️ タイムアップ！正解は: {locationName} でした",
        "stopWithAnswer": "🛑 ジオゲームを終了しました。正解は: {locationName} でした",
        "stop": "🛑 ジオゲームを終了しました。",
        "reveal": "📢 正解は: {locationName} でした！ {revealText}",
        "noScores": "このセッションのスコア記録はありません。",
        "sessionScores": "トッププレイヤー: {list}",
        "gameEndedScores": "🏁 ゲーム終了！最終セッションスコア: {list}",
        "finalScores": "🏁 最終セッションスコア: {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} が正解: {locationName}{timeString}{streakInfo}{pointsInfo}！ ",
            "timeout": "{roundPrefix}⏱️ タイムアップ！正解の場所は {locationName} でした。 ",
            "stopped": "{roundPrefix}🛑 ゲームを終了しました。正解の場所は {locationName} でした。 ",
            "reveal": "{roundPrefix}📢 正解は {locationName} でした！ "
        },
        "roundError": "ラウンド {currentRound} の正解発表中にエラーが発生しました。",
        "roundEnded": "ラウンドが終了しました。"
    }
};
