// src/locales/pt.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " em {seconds}s",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} pts)",
        "scoreEntry": "{rank}. {name} ({score} pts)",
        "roundText": {
            "one": "uma rodada",
            "many": "{totalRounds} rodadas"
        },
        "roundPrefixParen": "(Rodada {currentRound}/{totalRounds}) "
    },
    "trivia": {
        "start": "🎯 Iniciando {roundText} de Trivia! Tema: {topic}. Você tem {questionTimeSeconds} segundos para responder cada pergunta. Digite suas respostas no chat!",
        "roundPrefix": "[Rodada {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} TRIVIA: {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} acertou{timeString}{streakInfo}{pointsInfo}! A resposta é: {answer}. {explanation}",
        "timeout": "{roundPrefix}⏱️ Tempo esgotado! A resposta é: {answer}. {explanation}",
        "stop": "{roundPrefix}🛑 Jogo encerrado. A resposta era: {answer}",
        "nextRound": "🎮 Iniciando a Rodada {roundNumber} de {totalRounds}...",
        "noScores": "Nenhuma pontuação registrada.",
        "help": {
            "base": "🎮 Comandos do Trivia: !trivia (inicia um jogo de conhecimentos gerais), !trivia [tema] [rodadas] (tema específico), !trivia game [rodadas] (baseado no jogo atual da stream), !trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <opções...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". Mods podem usar comandos adicionais."
        },
        "gameStoppedScores": "🏁 Jogo encerrado. Pontuação final: {list}",
        "finalScores": "🏁 Pontuação final: {list}"
    },
    "riddle": {
        "start": "🤔 Iniciando {roundText} de Charadas! {topicText} Você tem {questionTimeSeconds} segundos para responder. Digite seus palpites no chat!",
        "topicText": "Tema: {topic}",
        "noTopicText": "Tenho uma charada para você!",
        "roundPrefix": "[Charada {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ CHARADA: {question} ({timeSeconds}s)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} acertou{timeString}{pointsInfo}! A resposta é: {answer}.{explanationText}",
        "timeout": "{roundPrefix}⏱️ Tempo esgotado! A resposta era: {answer}.{explanationText}",
        "stop": "{roundPrefix}🛑 Jogo de charadas encerrado.{explanationText}",
        "stopExplanation": " A resposta era: {answer}. {explanation}",
        "stopAnswerOnly": " A resposta era: {answer}.",
        "noScores": "Nenhuma pontuação registrada para esta sessão de charadas.",
        "sessionScores": "🏁 Melhores Jogadores da Sessão de Charadas: {list}",
        "noLeaderboard": "Nenhuma estatística de Charadas encontrada para #{channelName} ainda!",
        "leaderboard": "🏆 Mestres das Charadas em #{channelName}: {list}",
        "leaderboardEntry": "{rank}. {name} ({points} pts, {solved} resolvidas)",
        "help": {
            "base": "🤔 Comandos de Charada: !riddle (geral/jogo atual), !riddle <tema> [<rodadas>], !riddle <rodadas>, !riddle game [<rodadas>]",
            "common": ", !riddle leaderboard, !riddle report <motivo>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <fácil|normal|difícil> | questiontime <seg> | pointsbase <núm> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <núm> | keywordslimit <núm> | rounddelay <ms>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}O enigma terminou. A resposta era: {answer}. {explanation}"
    },
    "geo": {
        "startGame": "🎮 Geo-Game iniciado!{roundInfo} Adivinhe o local do jogo{gameTitleText}! {durationInfo} Digite seus palpites no chat! Primeira dica a caminho...",
        "startReal": "🌍 Geo-Game iniciado!{regionInfo}{roundInfo} Adivinhe a cidade, ponto turístico ou local do mundo real! {durationInfo} Digite seus palpites no chat! Primeira dica a caminho...",
        "roundInfo": " ({totalRounds} rodadas)",
        "durationInfo": "Você tem ⏱️ {roundDurationMinutes} minutos por rodada.",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (Região: {regionScope})",
        "nextRound": "🏁 Rodada {currentRound}/{totalRounds} começando agora! Boa sorte!",
        "clue": "❓ Dica {clueNumber}: {clueText}",
        "correctGuess": "✅ Parabéns @{displayName}! Você acertou: {locationName}{timeMsg}{streakInfo}{pointsInfo}!",
        "timeout": "⏱️ Tempo esgotado! A resposta correta era: {locationName}",
        "stopWithAnswer": "🛑 Geo-Game parado. A resposta era: {locationName}",
        "stop": "🛑 Geo-Game parado.",
        "reveal": "📢 A resposta era: {locationName}! {revealText}",
        "noScores": "Nenhuma pontuação registrada para esta sessão.",
        "sessionScores": "Melhores Jogadores: {list}",
        "gameEndedScores": "🏁 Jogo encerrado. Pontuação Final da Sessão: {list}",
        "finalScores": "🏁 Pontuação Final da Sessão: {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} acertou: {locationName}{timeString}{streakInfo}{pointsInfo}! ",
            "timeout": "{roundPrefix}⏱️ Tempo esgotado! O local era {locationName}. ",
            "stopped": "{roundPrefix}🛑 Jogo parado. O local era {locationName}. ",
            "reveal": "{roundPrefix}📢 A resposta era: {locationName}! "
        },
        "roundError": "Ocorreu um erro ao revelar a resposta da rodada {currentRound}.",
        "roundEnded": "A rodada terminou."
    }
};
