// src/locales/ru.js
// Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.

export default {
    "common": {
        "timeString": " за {seconds}с",
        "streakInfo": " 🔥x{streak}",
        "pointsInfo": " (+{points} очк.)",
        "scoreEntry": "{rank}. {name} ({score} очк.)",
        "roundText": {
            "one": "1 раунд",
            "many": "{totalRounds} раундов"
        },
        "roundPrefixParen": "(Раунд {currentRound}/{totalRounds}) "
    },
    "trivia": {
        "start": "🎯 Начинаем {roundText} викторины! Тема: {topic}. У вас {questionTimeSeconds} с на каждый вопрос. Пишите ответы в чат!",
        "roundPrefix": "[Раунд {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}{difficultyEmoji} ВИКТОРИНА: {question} ({timeSeconds}с)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} отвечает верно{timeString}{streakInfo}{pointsInfo}! Правильный ответ: {answer}. {explanation}",
        "timeout": "{roundPrefix}⏱️ Время вышло! Правильный ответ: {answer}. {explanation}",
        "stop": "{roundPrefix}🛑 Игра остановлена. Ответ был: {answer}",
        "nextRound": "🎮 Начинается раунд {roundNumber} из {totalRounds}...",
        "noScores": "Очки не набраны.",
        "help": {
            "base": "🎮 Команды викторины: !trivia (игра на общие темы), !trivia [тема] [раунды] (по конкретной теме), !trivia game [раунды] (по текущей игре стрима), !trivia leaderboard",
            "mod": ", !trivia stop, !trivia config <параметры...>, !trivia resetconfig, !trivia clearleaderboard",
            "nonMod": ". Модераторам доступны дополнительные команды."
        },
        "gameStoppedScores": "🏁 Игра остановлена. Итоговый счет: {list}",
        "finalScores": "🏁 Итоговый счет: {list}"
    },
    "riddle": {
        "start": "🤔 Начинаем {roundText} загадок! {topicText} У вас есть {questionTimeSeconds} сек., чтобы ответить. Пишите варианты в чат!",
        "topicText": "Тема: {topic}",
        "noTopicText": "У меня для вас загадка!",
        "roundPrefix": "[Загадка {roundNumber}/{totalRounds}] ",
        "question": "{roundPrefix}❓ ЗАГАДКА: {question} ({timeSeconds}с)",
        "correctAnswer": "{roundPrefix}✅ @{displayName} отгадал(а){timeString}{pointsInfo}! Правильный ответ: {answer}.{explanationText}",
        "timeout": "{roundPrefix}⏱️ Время вышло! Ответ был: {answer}.{explanationText}",
        "stop": "{roundPrefix}🛑 Игра в загадки остановлена.{explanationText}",
        "stopExplanation": " Ответ был: {answer}. {explanation}",
        "stopAnswerOnly": " Ответ был: {answer}.",
        "noScores": "Нет очков за эту сессию загадок.",
        "sessionScores": "🏁 Топ игроков сессии загадок: {list}",
        "noLeaderboard": "Для #{channelName} пока нет статистики по загадкам!",
        "leaderboard": "🏆 Мастера загадок в #{channelName}: {list}",
        "leaderboardEntry": "{rank}. {name} ({points} очк., {solved} отгадано)",
        "help": {
            "base": "🤔 Команды загадок: !riddle (общая/текущая игра), !riddle <тема> [<раунды>], !riddle <раунды>, !riddle game [<раунды>]",
            "common": ", !riddle leaderboard, !riddle report <причина>",
            "modStop": ", !riddle stop, !riddle clearleaderboard",
            "modConfig": ", !riddle config difficulty <easy|normal|hard> | questiontime <сек> | pointsbase <число> | pointstimebonus <true|false> | pointsdifficultymultiplier <true|false> | scoretracking <true|false> | maxrounds <число> | keywordslimit <число> | rounddelay <мс>",
            "modReset": ", !riddle resetconfig"
        },
        "gameOver": "{roundPrefix}Загадка завершена. Правильный ответ: {answer}. {explanation}"
    },
    "geo": {
        "startGame": "🎮 Гео-игра началась!{roundInfo} Угадайте локацию из игры{gameTitleText}! {durationInfo} Пишите варианты в чат! Первая подсказка на подходе...",
        "startReal": "🌍 Гео-игра началась!{regionInfo}{roundInfo} Угадайте реальный город, достопримечательность или место! {durationInfo} Пишите варианты в чат! Первая подсказка на подходе...",
        "roundInfo": " ({totalRounds} раундов)",
        "durationInfo": "У вас есть ⏱️ {roundDurationMinutes} мин на раунд.",
        "gameTitleText": " \"{gameTitle}\"",
        "regionInfo": " (Регион: {regionScope})",
        "nextRound": "🏁 Раунд {currentRound}/{totalRounds} начинается прямо сейчас! Удачи!",
        "clue": "❓ Подсказка {clueNumber}: {clueText}",
        "correctGuess": "✅ Поздравляем @{displayName}! Твой ответ: {locationName}{timeMsg}{streakInfo}{pointsInfo}!",
        "timeout": "⏱️ Время вышло! Правильный ответ: {locationName}",
        "stopWithAnswer": "🛑 Гео-игра остановлена. Ответ был: {locationName}",
        "stop": "🛑 Гео-игра остановлена.",
        "reveal": "📢 Ответ был: {locationName}! {revealText}",
        "noScores": "Нет очков за эту сессию.",
        "sessionScores": "Топ игроков: {list}",
        "gameEndedScores": "🏁 Игра окончена. Итоговый счет: {list}",
        "finalScores": "🏁 Итоговый счет сессии: {list}",
        "summaryPrefix": {
            "guessed": "{roundPrefix}✅ @{displayName} угадал: {locationName}{timeString}{streakInfo}{pointsInfo}! ",
            "timeout": "{roundPrefix}⏱️ Время вышло! Это было: {locationName}. ",
            "stopped": "{roundPrefix}🛑 Игра остановлена. Загаданное место: {locationName}. ",
            "reveal": "{roundPrefix}📢 Правильный ответ: {locationName}! "
        },
        "roundError": "Произошла ошибка при показе ответа для раунда {currentRound}.",
        "roundEnded": "Раунд завершён."
    }
};
