#!/usr/bin/env node
// scripts/translate-catalog.js
//
// Generates the non-English message catalogs in src/locales from en.js.
//
// Output is committed and reviewable — never fetched at runtime. Re-running is cheap: a sidecar
// hash file records the English source each translation was made from, so only new or changed keys
// are sent to the model. Without that, catalogs silently rot as English strings are edited.
//
// Usage:
//   node scripts/translate-catalog.js                    # fill in missing/changed keys, all locales
//   node scripts/translate-catalog.js --locales es,ja    # limit to specific locales
//   node scripts/translate-catalog.js --force            # re-translate everything
//   node scripts/translate-catalog.js --dry-run          # report what would change, call nothing
//   node scripts/translate-catalog.js --model <model-id> # override the translation model

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { initializeLlmClient, generateLiteContent } from '../src/components/llm/llmClient.js';
import { SUPPORTED_LOCALES, DEFAULT_LOCALE } from '../src/lib/i18n.js';
import {
    LANGUAGE_NAMES, DEFAULT_MODEL_ID, BATCH_SIZE,
    flatten, unflatten, hashOf, translateBatch, validate, parseFlag
} from './lib/catalogTranslator.js';

const LOCALES_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'locales');
const HASH_FILE = join(LOCALES_DIR, '.translation-hashes.json');

const readJson = (path, fallback) => (existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : fallback);

/** Loads a catalog ES module, or an empty object if it does not exist yet. */
async function readCatalog(code) {
    const path = join(LOCALES_DIR, `${code}.js`);
    if (!existsSync(path)) return {};
    const module = await import(`${path}?t=${Date.now()}`);
    return module.default || {};
}

/** Writes a catalog as an ES module, so i18n.js can import it without filesystem access. */
function writeCatalog(code, nested) {
    const note = code === DEFAULT_LOCALE
        ? 'Source of truth. Edit this file, then run: node scripts/translate-catalog.js'
        : 'Generated by scripts/translate-catalog.js from en.js. Review edits here; re-running preserves them unless the English source changed.';
    writeFileSync(join(LOCALES_DIR, `${code}.js`),
        `// src/locales/${code}.js\n// ${note}\n\nexport default ${JSON.stringify(nested, null, 4)};\n`);
}

async function main() {
    const args = process.argv.slice(2);
    const force = args.includes('--force');
    const dryRun = args.includes('--dry-run');
    const modelId = parseFlag(args, 'model') || process.env.TRANSLATION_MODEL_ID || DEFAULT_MODEL_ID;
    const localesFlag = parseFlag(args, 'locales');
    const requested = localesFlag
        ? localesFlag.split(',').filter(Boolean)
        : SUPPORTED_LOCALES.filter(c => c !== DEFAULT_LOCALE);

    const targets = requested.filter(code => {
        if (code === DEFAULT_LOCALE) return false;
        if (!LANGUAGE_NAMES[code]) {
            console.error(`Skipping unknown locale "${code}" — add it to LANGUAGE_NAMES and SUPPORTED_LOCALES first.`);
            return false;
        }
        return true;
    });

    const english = flatten(await readCatalog(DEFAULT_LOCALE));
    const englishKeys = Object.keys(english);
    if (!englishKeys.length) throw new Error(`No strings found in ${DEFAULT_LOCALE}.js`);
    console.log(`Source: ${englishKeys.length} keys in ${DEFAULT_LOCALE}.js`);
    console.log(`Model:  ${modelId}`);

    const hashes = readJson(HASH_FILE, {});

    // Initialize once up front rather than lazily inside each locale, which would race.
    // Always Gemini regardless of the runtime LLM_PROVIDER setting, so catalog output is
    // reproducible and does not change with the bot's provider flag.
    if (!dryRun && targets.length) initializeLlmClient();

    async function translateLocale(code) {
        const languageName = LANGUAGE_NAMES[code];
        const existing = flatten(await readCatalog(code));
        // Clone: mutating hashes[code] in place would persist hashes for keys whose catalog
        // was never written on an aborted run, and the next run would then skip them forever.
        const localeHashes = { ...(hashes[code] || {}) };
        // Drop hashes for keys no longer in English, or they accumulate forever. Committed
        // immediately: pruning is independent of whether any translation work happens below.
        let pruned = 0;
        for (const key of Object.keys(localeHashes)) {
            if (!(key in english)) { delete localeHashes[key]; pruned++; }
        }
        if (pruned) hashes[code] = localeHashes;

        const stale = englishKeys.filter(key =>
            force || existing[key] === undefined || localeHashes[key] !== hashOf(english[key]));
        const removed = Object.keys(existing).filter(key => !(key in english));

        if (!stale.length && !removed.length) {
            console.log(`${code}: up to date (${englishKeys.length} keys)`);
            return;
        }
        console.log(`${code}: ${stale.length} to translate, ${removed.length} obsolete to drop`);
        if (dryRun) {
            stale.slice(0, 10).forEach(key => console.log(`   would translate ${key}`));
            if (stale.length > 10) console.log(`   ...and ${stale.length - 10} more`);
            return;
        }

        // Start from the existing catalog, drop obsolete keys, then fill in the stale ones.
        let updated = 0;
        const result = {};
        for (const key of englishKeys) if (existing[key] !== undefined) result[key] = existing[key];

        for (let i = 0; i < stale.length; i += BATCH_SIZE) {
            const batch = stale.slice(i, i + BATCH_SIZE);
            const entries = batch.map(key => ({ key, text: english[key] }));
            process.stdout.write(`   ${code} batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} keys... `);
            let translations;
            try {
                translations = await translateBatch(generateLiteContent, languageName, entries, modelId);
            } catch (err) {
                console.log(`FAILED (${err.message}) — keeping previous values for this batch`);
                continue;
            }
            let ok = 0;
            for (const key of batch) {
                const translated = translations.get(key);
                const problem = validate(english[key], translated);
                if (problem) {
                    console.log(`\n     ! ${key}: ${problem} — left untranslated`);
                    continue;
                }
                result[key] = translated;
                localeHashes[key] = hashOf(english[key]);
                ok++;
                updated++;
            }
            console.log(`${ok}/${batch.length} ok`);
        }

        const missing = englishKeys.filter(key => result[key] === undefined);
        if (missing.length) {
            // The all-locales-share-one-key-set invariant is what isCatalogued() depends on, so an
            // incomplete catalog must not be written — it would make lookups fall back mid-message
            // and mix two languages inside a single string.
            console.error(`${code}: ABORTED — ${missing.length} key(s) still missing (${missing.slice(0, 5).join(', ')}). Catalog not written.`);
            return;
        }
        if (updated === 0 && !removed.length) {
            console.error(`${code}: no keys translated (all batches failed). Catalog left unchanged.`);
            return;
        }

        writeCatalog(code, unflatten(result));
        hashes[code] = localeHashes;
        console.log(`${code}: wrote ${englishKeys.length} keys to ${code}.js (${updated} newly translated, ${removed.length} dropped)`);
    }

    // Locales are independent: each writes its own file and its own hashes entry. Bounded rather
    // than all-at-once because this API returns 503 "high demand" under load, and firing eight
    // concurrent streams trades a slow run for a failed one.
    const CONCURRENCY = 3;
    const queue = [...targets];
    await Promise.all(Array.from({ length: Math.min(CONCURRENCY, queue.length) }, async () => {
        while (queue.length) {
            await translateLocale(queue.shift());
        }
    }));

    if (!dryRun) writeFileSync(HASH_FILE, JSON.stringify(hashes, null, 2) + '\n');
    console.log('Done.');
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
