name: Deploy ChatSage to Cloud Run
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README-*.md'
      - 'docs/**'
      - 'docs/**'

env:
  GCP_PROJECT_ID: 'streamsage-bot'
  GCP_REGION: 'us-central1'
  CLOUD_RUN_SERVICE_NAME: 'chatsage'
  TWITCH_BOT_USERNAME: 'ChatSageBot'
  TWITCH_BOT_USERNAME: 'ChatSageBot'
  TWITCH_CHANNELS_SECRET_NAME: 'projects/907887386166/secrets/twitch-channels/versions/latest'
  GEMINI_MODEL_ID: 'gemini-2.5-flash-lite'
  GEMINI_MODEL_ID: 'gemini-2.5-flash-lite'
  LOG_LEVEL: 'info'
  STREAM_INFO_FETCH_INTERVAL_SECONDS: '120'
  NODE_ENV: 'production'
  PINO_PRETTY_LOGGING: 'false'
  TWITCH_BOT_REFRESH_TOKEN_SECRET_NAME: 'projects/907887386166/secrets/TWITCH_BOT_REFRESH_TOKEN/versions/latest'
  LAZY_CONNECT: 'true'
  PUBLIC_URL: 'https://chatsage-907887386166.us-central1.run.app'
  KEEP_ALIVE_QUEUE: 'self-ping'
  GOOGLE_CLOUD_PROJECT: 'streamsage-bot'
  EVENTSUB_BYPASS: '0'
  ALLOWED_CHANNELS_SECRET_NAME: 'projects/907887386166/secrets/allowed-channels/versions/latest'
  WEBUI_BASE_URL: 'https://webui-zpqjdsguqa-uc.a.run.app'
  WEBUI_INTERNAL_TOKEN: 'projects/907887386166/secrets/webui-internal-token'

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Debug Info
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Actor: ${{ github.actor }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/907887386166/locations/global/workloadIdentityPools/ghactions-pool/providers/ghactions-provider'
          service_account: 'cloud-run-deployer@streamsage-bot.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run via gcloud CLI
        id: deploy
        run: |
          DEPLOYED_URL=$(gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
            --source . \
            --region ${{ env.GCP_REGION }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --min-instances=0 \
            --set-env-vars="NODE_ENV=${{ env.NODE_ENV }},LOG_LEVEL=${{ env.LOG_LEVEL }},PINO_PRETTY_LOGGING=${{ env.PINO_PRETTY_LOGGING }},TWITCH_BOT_USERNAME=${{ env.TWITCH_BOT_USERNAME }},TWITCH_CHANNELS_SECRET_NAME=${{ env.TWITCH_CHANNELS_SECRET_NAME }},GEMINI_MODEL_ID=${{ env.GEMINI_MODEL_ID }},STREAM_INFO_FETCH_INTERVAL_SECONDS=${{ env.STREAM_INFO_FETCH_INTERVAL_SECONDS }},PUBLIC_URL=${{ env.PUBLIC_URL }},LAZY_CONNECT=${{ env.LAZY_CONNECT }},TWITCH_BOT_REFRESH_TOKEN_SECRET_NAME=${{ env.TWITCH_BOT_REFRESH_TOKEN_SECRET_NAME }},KEEP_ALIVE_QUEUE=${{ env.KEEP_ALIVE_QUEUE }},GOOGLE_CLOUD_PROJECT=${{ env.GOOGLE_CLOUD_PROJECT }},WEBUI_BASE_URL=${{ env.WEBUI_BASE_URL }},WEBUI_INTERNAL_TOKEN=${{ env.WEBUI_INTERNAL_TOKEN }}" \
            --set-secrets="GEMINI_API_KEY=STREAM_SAGE_GEMINI_API_KEY:latest,TWITCH_CLIENT_ID=STREAM_SAGE_TWITCH_CLIENT_ID:latest,TWITCH_CLIENT_SECRET=STREAM_SAGE_TWITCH_CLIENT_SECRET:latest,TWITCH_EVENTSUB_SECRET=twitch-eventsub-secret:latest" \
            --allow-unauthenticated \
            --min-instances=0 \
            --set-env-vars="NODE_ENV=${{ env.NODE_ENV }},LOG_LEVEL=${{ env.LOG_LEVEL }},PINO_PRETTY_LOGGING=${{ env.PINO_PRETTY_LOGGING }},TWITCH_BOT_USERNAME=${{ env.TWITCH_BOT_USERNAME }},TWITCH_CHANNELS_SECRET_NAME=${{ env.TWITCH_CHANNELS_SECRET_NAME }},GEMINI_MODEL_ID=${{ env.GEMINI_MODEL_ID }},STREAM_INFO_FETCH_INTERVAL_SECONDS=${{ env.STREAM_INFO_FETCH_INTERVAL_SECONDS }},PUBLIC_URL=${{ env.PUBLIC_URL }},LAZY_CONNECT=${{ env.LAZY_CONNECT }},TWITCH_BOT_REFRESH_TOKEN_SECRET_NAME=${{ env.TWITCH_BOT_REFRESH_TOKEN_SECRET_NAME }},KEEP_ALIVE_QUEUE=${{ env.KEEP_ALIVE_QUEUE }},GOOGLE_CLOUD_PROJECT=${{ env.GOOGLE_CLOUD_PROJECT }},WEBUI_BASE_URL=${{ env.WEBUI_BASE_URL }},WEBUI_INTERNAL_TOKEN=${{ env.WEBUI_INTERNAL_TOKEN }}" \
            --set-secrets="GEMINI_API_KEY=STREAM_SAGE_GEMINI_API_KEY:latest,TWITCH_CLIENT_ID=STREAM_SAGE_TWITCH_CLIENT_ID:latest,TWITCH_CLIENT_SECRET=STREAM_SAGE_TWITCH_CLIENT_SECRET:latest,TWITCH_EVENTSUB_SECRET=twitch-eventsub-secret:latest" \
            --labels="managed-by=github-actions,commit-sha=${{ github.sha }}" \
            --format="get(status.url)")
          echo "url=$DEPLOYED_URL" >> $GITHUB_OUTPUT

      - name: Show Deployment URL
        run: |
          echo "Deployed to Cloud Run: ${{ steps.deploy.outputs.url }}"